// MergeCrew RunnerProfile -> Gas City agent config exporter. ADR-0016 step 4, first slice.
//
// MergeCrew places work on a runner: a RunnerProfile holds the placement kind and the cloud
// account, and a RunnerAgent holds the enrolled agent name and a token hash. Gas City places work
// with an agent config: the runtime axis, the work directory, the wake mode, and the pool size.
// This module converts one into the other. Zero dependencies.
//
// Usage:
//   node ops/gc/agents-export.mjs --from-json=profile.json --name=dev-1 --rig=mergecrew [--out=<dir>]
//
// Test: node --test ops/gc/test/agents-export.test.mjs

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** MergeCrew runner kinds -> Gas City runtime values. */
const RUNTIME_BY_KIND = {
  none: 'local',
  local: 'local',
  fargate_byo: 'k8s',
  k8s: 'k8s',
};

/** Fields that Gas City does not model. The exporter reports them instead of dropping them. */
const UNMAPPED_FIELDS = [
  ['awsRoleArn', 'Gas City does not assume a cloud role. Keep the role in MergeCrew.'],
  ['awsExternalId', 'Gas City does not assume a cloud role. Keep the external id in MergeCrew.'],
  ['tokenHash', 'Gas City manages session identity. The MergeCrew token hash is not needed.'],
];

export function runtimeForKind(kind) {
  const value = RUNTIME_BY_KIND[String(kind ?? 'none')];
  if (!value) throw new Error(`runtimeForKind: unknown runner kind "${kind}"`);
  return value;
}

export function agentName(rig, name) {
  if (!name) throw new Error('agentName: name is required');
  return rig ? `${rig}/${name}` : String(name);
}

/** Map a MergeCrew runner profile to a Gas City agent config. */
export function runnerProfileToAgent(profile = {}, options = {}) {
  const name = options.name ?? profile.name;
  if (!name) throw new Error('runnerProfileToAgent: name is required');
  const kind = profile.kind ?? 'none';
  const runtime = runtimeForKind(kind);

  const min = Number.isFinite(profile.minActiveSessions) ? Number(profile.minActiveSessions) : 0;
  const max = Number.isFinite(profile.maxActiveSessions) ? Number(profile.maxActiveSessions) : 1;
  if (max < min) throw new Error(`runnerProfileToAgent: max ${max} is below min ${min}`);

  const notes = [];
  if (kind === 'fargate_byo') {
    notes.push('MergeCrew ran this agent on a customer AWS account. Gas City runs it on the k8s runtime.');
  }
  for (const [field, reason] of UNMAPPED_FIELDS) {
    if (profile[field] !== undefined && profile[field] !== null && profile[field] !== '') {
      notes.push(`Unmapped field ${field}: ${reason}`);
    }
  }

  return {
    name: agentName(options.rig, name),
    scope: options.scope ?? 'rig',
    runtime,
    wake_mode: options.wakeMode ?? 'fresh',
    work_dir: options.workDir ?? '.gc/worktrees/{{.Rig}}/{{.AgentBase}}',
    idle_timeout: options.idleTimeout ?? '2h',
    min_active_sessions: min,
    max_active_sessions: max,
    harness: options.harness ?? 'claude',
    model: options.model ?? 'auto/best-coding',
    nudge: options.nudge ?? 'Run gc hook --claim --json now; if it returns work, run the claimed formula.',
    skills: options.skills ?? ['core.gc-city', 'core.gc-work', 'core.gc-agents', 'core.gc-dispatch'],
    notes,
  };
}

function quote(text) {
  return JSON.stringify(String(text));
}

export function renderAgentToml(agent) {
  const lines = ['# Generated by ops/gc/agents-export.mjs. Do not edit by hand.'];
  for (const note of agent.notes ?? []) lines.push(`# ${note}`);
  lines.push(`name = ${quote(agent.name)}`);
  lines.push(`scope = ${quote(agent.scope)}`);
  lines.push(`runtime = ${quote(agent.runtime)}`);
  lines.push(`wake_mode = ${quote(agent.wake_mode)}`);
  lines.push(`work_dir = ${quote(agent.work_dir)}`);
  lines.push(`harness = ${quote(agent.harness)}`);
  lines.push(`model = ${quote(agent.model)}`);
  lines.push(`idle_timeout = ${quote(agent.idle_timeout)}`);
  lines.push(`min_active_sessions = ${agent.min_active_sessions}`);
  lines.push(`max_active_sessions = ${agent.max_active_sessions}`);
  lines.push(`nudge = ${quote(agent.nudge)}`);
  lines.push(`skills = [${(agent.skills ?? []).map(quote).join(', ')}]`);
  return `${lines.join('\n')}\n`;
}

export function exportAgent(profile, options = {}) {
  const agent = runnerProfileToAgent(profile, options);
  return { agent, toml: renderAgentToml(agent) };
}

function main(argv) {
  const args = argv.slice(2);
  const arg = (flag) => args.find((a) => a.startsWith(`${flag}=`))?.split('=').slice(1).join('=');
  const path = arg('--from-json');
  if (!path) {
    console.error('usage: node ops/gc/agents-export.mjs --from-json=<profile.json> --name=<agent> --rig=<rig> [--out=<dir>]');
    return 2;
  }
  const profile = JSON.parse(readFileSync(path, 'utf8'));
  const { agent, toml } = exportAgent(profile, {
    name: arg('--name'),
    rig: arg('--rig'),
    model: arg('--model'),
    harness: arg('--harness'),
  });
  const out = arg('--out');
  if (out) {
    const dir = join(out, agent.name.replace(/\//g, '--'));
    mkdirSync(dir, { recursive: true });
    const file = join(dir, 'agent.toml');
    writeFileSync(file, toml);
    console.log(file);
  } else {
    console.log(toml);
  }
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv));
}
