// MergeCrew lifecycle -> Gas City formula exporter. ADR-0016 step 2, first slice.
//
// MergeCrew keeps its lifecycle as MergecrewConfig JSON (see packages/domain/src/lifecycle-templates.ts).
// Gas City runs work from a formula (v2 graph). This module converts one into the other.
// Zero dependencies.
//
// Usage:
//   node ops/gc/formula-export.mjs --from-json=t.json --out=/home/haoye/gascity/formulas
//   node ops/gc/formula-export.mjs --from-json=t.json --print
//
// Test: node --test ops/gc/test/formula-export.test.mjs

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const COMPILER_REQUIREMENT = '>=2.0.0';

/** Agent kinds that run after the reviewer and only land the change. */
const LANDING_STEP_ID = 'land';

function asArray(value) {
  return Array.isArray(value) ? value : [];
}

function slug(text) {
  return String(text)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** MergeCrew template id -> formula name. */
export function formulaName(templateId) {
  const id = slug(templateId);
  if (!id) throw new Error('formulaName: templateId is required');
  return `mol-mc-${id}`;
}

/** Read the workflow agent order. The first workflow in the config wins. */
export function workflowAgents(config) {
  const workflows = asArray(config?.lifecycle?.workflows);
  if (workflows.length === 0) throw new Error('workflowAgents: lifecycle.workflows is empty');
  const agents = asArray(workflows[0].agents);
  if (agents.length === 0) throw new Error('workflowAgents: the first workflow has no agents');
  return agents.map(String);
}

function stepDescription(agentName, agent, template) {
  const lines = [];
  lines.push(`Role: ${agent?.kind ?? agentName}.`);
  if (agent?.description) lines.push(String(agent.description).trim());
  const skills = asArray(agent?.skills);
  if (skills.length) {
    lines.push('');
    lines.push('Tools in scope:');
    for (const skill of skills) lines.push(`- ${skill}`);
  }
  const steps = agent?.maxStepsPerRun;
  const calls = agent?.maxToolCallsPerStep;
  if (steps || calls) {
    lines.push('');
    lines.push(`Budget: ${steps ?? 'n/a'} steps, ${calls ?? 'n/a'} tool calls per step.`);
  }
  lines.push('');
  lines.push('Read the work bead for the task. Report the result in the bead, then stop.');
  if (template?.name) lines.push('');
  lines.push(`Exported from the MergeCrew lifecycle template "${template.id}" (${template.name}).`);
  return lines.join('\n');
}

/** Build the formula model. Pure function: the same input always gives the same output. */
export function templateToFormula(template) {
  if (!template?.id) throw new Error('templateToFormula: template.id is required');
  const config = template.parsed ?? template.config;
  if (!config) throw new Error('templateToFormula: template.parsed is required');
  const agents = workflowAgents(config);
  const agentConfig = config?.agents ?? {};

  const steps = [];
  let previous = null;
  for (const agentName of agents) {
    const id = slug(agentName) || agentName;
    const agent = agentConfig[agentName] ?? {};
    const step = {
      id,
      title: `${agent.kind ?? agentName}: ${agent.description ? firstSentence(agent.description) : agentName}`,
      description: stepDescription(agentName, agent, template),
      needs: previous ? [previous] : [],
    };
    steps.push(step);
    previous = id;
  }

  steps.push({
    id: LANDING_STEP_ID,
    title: 'Land the change: branch, checks, pull request',
    description: [
      'Take the reviewed change and land it as a pull request.',
      '',
      '- Create one branch for the work bead.',
      '- Run the checks the repository defines.',
      '- Open a pull request and put the check output in the body.',
      '- Do not push to the default branch. Do not force push.',
      '',
      `Exported from the MergeCrew lifecycle template "${template.id}".`,
    ].join('\n'),
    needs: previous ? [previous] : [],
  });

  return {
    formula: formulaName(template.id),
    description: [
      `MergeCrew lifecycle "${template.name ?? template.id}" as a Gas City formula.`,
      '',
      `Stack: ${asArray(template.stack).join(', ') || 'unspecified'}`,
      '',
      'Generated by ops/gc/formula-export.mjs (ADR-0016 step 2).',
      'Edit the MergeCrew template, then export again. Do not edit the generated file by hand.',
    ].join('\n'),
    compiler: COMPILER_REQUIREMENT,
    vars: {
      work_bead: { description: 'Bead that carries the task', default: '' },
    },
    steps,
  };
}

function firstSentence(text) {
  const clean = String(text).trim().replace(/\s+/g, ' ');
  const cut = clean.split(/(?<=[.!?])\s/)[0];
  return cut.length > 80 ? `${cut.slice(0, 77)}...` : cut;
}

/** TOML basic multiline string. Backslashes and quotes are escaped. */
export function tomlString(text) {
  const body = String(text).replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
  return `"""\n${body}\n"""`;
}

export function renderFormulaToml(formula) {
  const out = [];
  out.push(`# Generated by ops/gc/formula-export.mjs. Do not edit by hand.`);
  out.push(`description = ${tomlString(formula.description)}`);
  out.push('');
  out.push(`formula = ${JSON.stringify(formula.formula)}`);
  out.push('');
  out.push('[requires]');
  out.push(`formula_compiler = ${JSON.stringify(formula.compiler)}`);
  out.push('');
  for (const [name, spec] of Object.entries(formula.vars ?? {})) {
    out.push(`[vars.${name}]`);
    out.push(`description = ${JSON.stringify(spec.description ?? '')}`);
    out.push(`default = ${JSON.stringify(spec.default ?? '')}`);
    out.push('');
  }
  for (const step of formula.steps) {
    out.push('[[steps]]');
    out.push(`id = ${JSON.stringify(step.id)}`);
    out.push(`title = ${JSON.stringify(step.title)}`);
    out.push(`description = ${tomlString(step.description)}`);
    if (step.needs?.length) out.push(`needs = ${JSON.stringify(step.needs)}`);
    out.push('');
  }
  return `${out.join('\n').trimEnd()}\n`;
}

export function exportFormula(template) {
  const formula = templateToFormula(template);
  return { formula, toml: renderFormulaToml(formula) };
}

function main(argv) {
  const args = argv.slice(2);
  const path = args.find((a) => a.startsWith('--from-json='))?.split('=')[1];
  const outDir = args.find((a) => a.startsWith('--out='))?.split('=')[1];
  const print = args.includes('--print');
  if (!path) {
    console.error('usage: node ops/gc/formula-export.mjs --from-json=<template.json> [--out=<dir>|--print]');
    return 2;
  }
  const template = JSON.parse(readFileSync(path, 'utf8'));
  const { formula, toml } = exportFormula(template);
  if (outDir) {
    mkdirSync(outDir, { recursive: true });
    const file = join(outDir, `${formula.formula}.toml`);
    writeFileSync(file, toml);
    console.log(file);
  }
  if (print || !outDir) console.log(toml);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv));
}
