// MergeCrew Schedule -> Gas City order exporter. ADR-0016 step 3, first slice.
//
// MergeCrew keeps one Schedule row per project (cron + timezone + skip dates). Gas City runs
// timed work from an order (trigger = "cron"). This module converts one into the other.
//
// The exporter refuses a schedule that fires more often than every five minutes. On 2026-10-05 a
// set of per-minute writers dropped the Dolt connection and blocked session start. See ADR-0016.
//
// Zero dependencies.
//
// Usage:
//   node ops/gc/orders-export.mjs --from-json=s.json --name=project-tick --exec='node ops/pipeline/tick.mjs'
//
// Test: node --test ops/gc/test/orders-export.test.mjs

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** The lowest allowed minute step. Anything faster is a Dolt churn risk. */
export const MIN_MINUTE_STEP = 5;

/**
 * Read the minute field of a five-field cron expression.
 * Throws when the expression is not five fields, or when it fires too often.
 */
export function checkCron(expression, { minStep = MIN_MINUTE_STEP } = {}) {
  const fields = String(expression).trim().split(/\s+/);
  if (fields.length !== 5) {
    throw new Error(`checkCron: expected 5 fields, got ${fields.length} in "${expression}"`);
  }
  const [minute] = fields;
  if (minute === '*') {
    throw new Error(`checkCron: "${expression}" fires every minute. The minimum step is ${minStep} minutes.`);
  }
  const step = minute.match(/^\*\/(\d+)$/);
  if (step) {
    const value = Number(step[1]);
    if (!Number.isFinite(value) || value < minStep) {
      throw new Error(`checkCron: "${expression}" fires every ${step[1]} minute(s). The minimum step is ${minStep} minutes.`);
    }
    return expression.trim();
  }
  const range = minute.match(/^(\d+)-(\d+)$/);
  if (range) {
    const span = Number(range[2]) - Number(range[1]) + 1;
    if (span > 1 && span < minStep) {
      throw new Error(`checkCron: "${expression}" covers ${span} minutes. The minimum step is ${minStep} minutes.`);
    }
    return expression.trim();
  }
  if (/^[\d,]+$/.test(minute)) {
    const values = minute.split(',').map(Number).sort((a, b) => a - b);
    for (let i = 1; i < values.length; i += 1) {
      if (values[i] - values[i - 1] < minStep) {
        throw new Error(`checkCron: "${expression}" has minutes less than ${minStep} apart.`);
      }
    }
    return expression.trim();
  }
  throw new Error(`checkCron: unsupported minute field "${minute}"`);
}

function quote(text) {
  return JSON.stringify(String(text));
}

/** Map one MergeCrew Schedule row to an order model. */
export function scheduleToOrder(schedule, options = {}) {
  if (!schedule) throw new Error('scheduleToOrder: schedule is required');
  const cron = checkCron(schedule.cron ?? '', options);
  const name = options.name ?? `mc-${schedule.projectId ?? 'project'}`;
  const timezone = schedule.timezone ?? 'UTC';
  const skipDates = Array.isArray(schedule.skipDates) ? schedule.skipDates : [];
  const enabled = schedule.enabled !== false;

  const notes = [];
  notes.push(`MergeCrew schedule for project ${schedule.projectId ?? 'unknown'}.`);
  notes.push(`Time zone in MergeCrew: ${timezone}. Gas City cron uses the host time zone; verify the offset.`);
  if (skipDates.length) notes.push(`Skip dates in MergeCrew: ${skipDates.join(', ')}. Handle them in the exec command.`);
  if (!enabled) notes.push('The MergeCrew schedule is disabled. Enable the order before use.');

  return {
    name,
    description: notes.join(' '),
    trigger: 'cron',
    cron,
    exec: options.exec ?? '',
    timeout: options.timeout ?? '1h',
    enabled,
    notes,
  };
}

export function renderOrderToml(order) {
  const lines = ['# Generated by ops/gc/orders-export.mjs. Do not edit by hand.'];
  if (!order.enabled) lines.push('# Disabled in MergeCrew. Enable the order before use.');
  lines.push('[order]');
  lines.push(`description = ${quote(order.description)}`);
  lines.push(`trigger = ${quote(order.trigger)}`);
  lines.push(`schedule = ${quote(order.cron)}`);
  if (order.exec) lines.push(`exec = ${quote(order.exec)}`);
  if (order.timeout) lines.push(`timeout = ${quote(order.timeout)}`);
  return `${lines.join('\n')}\n`;
}

export function exportOrder(schedule, options = {}) {
  const order = scheduleToOrder(schedule, options);
  return { order, toml: renderOrderToml(order) };
}

function main(argv) {
  const args = argv.slice(2);
  const arg = (flag) => args.find((a) => a.startsWith(`${flag}=`))?.split('=').slice(1).join('=');
  const path = arg('--from-json');
  const outDir = arg('--out');
  if (!path) {
    console.error('usage: node ops/gc/orders-export.mjs --from-json=<schedule.json> --name=<order> --exec=<cmd> [--out=<dir>]');
    return 2;
  }
  const schedule = JSON.parse(readFileSync(path, 'utf8'));
  const { order, toml } = exportOrder(schedule, {
    name: arg('--name'),
    exec: arg('--exec'),
    timeout: arg('--timeout'),
  });
  if (outDir) {
    mkdirSync(outDir, { recursive: true });
    const file = join(outDir, `${order.name}.toml`);
    writeFileSync(file, toml);
    console.log(file);
  } else {
    console.log(toml);
  }
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv));
}
